### ISSUE TITLE
No Reaction to Export - iPad

### ISSUE THREAD

**Issue by iLiftALot** [holxsam/tldraw-in-obsidian#41]
I'm running the latest versions of iOS on iPad at the moment and cannot get the export option to work. There is no reaction when I select any of the export options. I don't see any errors pop up in the dev console or screen at all.

**Comment by jon-dez** [comment]
I found the underlying issue, well at least on Android. It has to do with how web-views are implemented on mobile so I'm assuming it is the same for iOS. On desktop, a filesystem picker pops up letting you save to anywhere, but on mobile nothing pops up due to how filesystem permissions are managed in a web-view.  I will be working on implementing a workaround so that a copy file is instead saved to a location inside the vault. From there you will be able to then click on the new file and press the share button that Obsidian provides to export outside of your vault.

**Comment by iLiftALot** [comment]
> I found the underlying issue, well at least on Android. It has to do with how web-views are implemented on mobile so I'm assuming it is the same for iOS. On desktop, a filesystem picker pops up letting you save to anywhere, but on mobile nothing pops up due to how filesystem permissions are managed in a web-view.  I will be working on implementing a workaround so that a copy file is instead saved to a location inside the vault. From there you will be able to then click on the new file and press the share button that Obsidian provides to export outside of your vault.

Awesome thank you.

The school year has arrived and calculus comes with that 😅 I'll definitely need to utilize the export option. I'll be looking for your implementation.

While I have your attention for the moment, I have a side issue that I haven't been able to figure out yet. It's a little off topic, but it definitely sways way more to your side of expertise than mine:

**How do people ensure their Obsidian plugins are compatible on mobile devices?**

I'm always getting some sort of error on the plugins I create for my own personal usage, most recently for the use of the `process` object.

That might be a loaded question with a lot of different answers pertaining to specific CSS styles and their compatibility with mobile devices etc... but if you could just point me in the right direction, you'd be a life saver.

I appreciate your time!

**Comment by jon-dez** [comment]
@iLiftALot I followed this [guide](https://docs.obsidian.md/Plugins/Getting+started/Mobile+development) from the Obsidian docs in order to setup my android phone to allow remote debugging. Also, when I want to test if it works on my device I use the `adb` command to copy over the main.js, style.css, and manifest.json to the plugin folder on my android and restart obsidian, for iOS I don't know how this is done.

**Comment by jon-dez** [comment]
Could you try this out and report back to me if this works on iOS?

https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.4.0-preview.2

**Comment by iLiftALot** [comment]
> Could you try this out and report back to me if this works on iOS?
> 
> 
> 
> https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.4.0

I tried all options on both my iPad and iPhone, same result.

Didn't see anything in the dev console either.

**Comment by jon-dez** [comment]
@iLiftALot I'm a dummy, when you mentioned "export " I thought the entire time you meant the "Save as copy" button. Anyways here is another attempt at a fix:

https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.4.1

**Comment by iLiftALot** [comment]
> @iLiftALot No problem, happy to help! BTW I'm a dummy, when you mentioned "export " I thought the entire time you meant the "Save as copy" button. Anyways here is another attempt at a fix:
> 
> 
> 
> https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.4.1

We're almost in the clear!

That worked awesome, except for the fact that it saves every file as "Untitled" despite specifying a name within the text input. Not even a big deal, I'm just glad it's working now.

I'm very curious, what was causing the issue and how did you fix it?

**Comment by jon-dez** [comment]
Whoops, my mistake. It was something I overlooked while doing some refactoring. Pushing a fix shortly.

**Comment by jon-dez** [comment]
https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.4.2

**Comment by jon-dez** [comment]
@iLiftALot Have you had the time to test the most recent release?

**Comment by iLiftALot** [comment]
> @iLiftALot Have you had the time to test the most recent release?

Sorry man, things got busy very fast. Standby, on it now.

**Comment by iLiftALot** [comment]
> @iLiftALot Have you had the time to test the most recent release?

Works perfectly, sorry for the wait. Thanks!

**Comment by jon-dez** [comment]
No problem!
