### ISSUE TITLE
Documentation for embeds

### ISSUE THREAD

**Issue by jon-dez** [holxsam/tldraw-in-obsidian#59]
This is not an issue; this is documentation.

# Formatting an embed

`![[<embed_arguments>]]`

There are three `embed_arguments`, and they must appear in the order listed below. Each argument must be separated by the pipe character `|`.

- Required: `<tldraw_markdown_file>`: This must be a valid tldraw file you created.
- Optional: `<alt_text>`: Controls the bounds of the tldraw file
- Optional: `<embed_size>`: Controls the size of the embed without affecting the tldraw file bounds

Thus, we have the following configurations possible:

`![[<tldraw_markdown_file>]]`

`![[<tldraw_markdown_file>|<alt_text>]]`

`![[<tldraw_markdown_file>|<embed_size>]]`

`![[<tldraw_markdown_file>|<alt_text>|<embed_size>]]`

> Do not include the `<` and `>` brackets in the arguments

## Using `<alt_text>`

  - `size` and `pos` fields are available to use in the "alt" text of the embed,
  - `size=<width>,<height>`
  - `pos=<x_offset>,<y_offset>`
  - `pos` field is optional
  - separate each field with `;`, e.g. `size=1280,720;pos=500,20`

Example:

If you have an embed called `my-embed.md` you could do `![[my-embed.md|pos=525,185;size=100,120]]` where the "alt" text is `pos=525,185;size=100,120`. Note that there is a semicolon separating the two fields.

## Using `<embed_size>`

- `<width>x<height>`

Example:

If you have an embed called `my-embed.md` you could do `![[my-embed.md|200x100]]`. Note that there is an `x` separating the two numbers.

# Feature demos

## Live updates

https://github.com/user-attachments/assets/472cf2c5-eec9-4551-b2ed-7a8c7549d6b9

## Set embed size

https://github.com/user-attachments/assets/594ba52c-7680-494e-bf4c-172743b16267

## Set bounds on embed

Have to do this manually at this point in time.

1. Show embed menu and enter interactive mode (right click or tap and hold on mobile)
2. Adjust the embed
3. Exit interact mode
4. Show embed menu and select "Copy bounds"
5. Paste into the alt text portion of the embed link

https://github.com/user-attachments/assets/40610222-120a-4e28-8183-660d3382911c

**Comment by Maksim3l** [comment]
I came here to find how to embed a specific page; and have found an answer though browsing the code and making educated guesses so I will add this here

to embed a specific page from multiple; 

# How to embed pages

**1st** click on this icon to see the markdown code:
![Image](https://github.com/user-attachments/assets/f0a9c54e-7112-44f1-a2b9-4d2040fa1f6c)

**2nd** Ctrl + f and search for your page name 

![Image](https://github.com/user-attachments/assets/d808a0a2-00dc-45cb-8ea5-7b3eef261eba)

**3rd** Copy the page id

![Image](https://github.com/user-attachments/assets/45a42b8a-c52b-448d-814c-b0912b7c3633)

**4th** Add to the embed

![Image](https://github.com/user-attachments/assets/7428a935-ac93-461b-abc9-d20ffc4b12b0)

I've written this here in case someone (like me) didn't know how to get to the page id because the page name dosen't work. Otherwise: love this plugin ty for the hard work; feel free to delete this comment once the documentation is updated
