### ISSUE TITLE
Tldraw Not Opening as soon you embed 

### ISSUE THREAD

**Issue by MohamedKelif** [holxsam/tldraw-in-obsidian#64]
if you use the command: **Create New drawings and embed as attachment**. its leaves a empty frame on the notes unless you toggle on the setting:  (show background or show background dotted pattern). then you will see the actual embed. there is no way to open the drawing unless you find the links on either outgoing links or backlinks. i found a bit of hack of opening the drawings directly from the notes without using the outgoing links. you have to long click from ipad or right click on windows on the embeds itself. then it opens small dialog that says "Edit drawings (new tab)". 

User like my self would appreciate a quality of life improving of allowing Tldraw to automatically open as soon we embed it as attachment. or have option to click the  link or click the embedded frame to open Tldraw. honestly i prefer not having the show background option on as i like my embeds with not background so they match my notes seamlessly. 

Thank you for making this amazing plugin  

see attached for your reference

With Background On

![with background on ](https://github.com/user-attachments/assets/61889360-df8d-446f-bb0a-0c8c8fb2153d)

with no background - with dialog open 
![with no background on ](https://github.com/user-attachments/assets/99981980-3380-41c6-8c5f-d7a958ea633d)

**Comment by MohamedKelif** [comment]
![with no background - dialog ](https://github.com/user-attachments/assets/88a429f9-4915-4079-a033-084c07bfdcdf)

**Comment by jon-dez** [comment]
Good catch, here are some solutions to this I can think of implementing:

- If it is a new drawing, then the embed should display an edit button
- Add variations to the "Create New drawing and embed as attachment" command
  - "Create New drawing and embed as attachment (edit in new tab)"
  - "Create New drawing and embed as attachment (edit in new tab - split horizontal)"
  - "Create New drawing and embed as attachment (edit in new tab - split vertically)"
  
Let me know what you think!

**Comment by MohamedKelif** [comment]
Thats amazing Thanks you so much - Will the edit button disappear? it shouldn't interfere with drawings it self. I think excalidraw solved this as soon you embed it opens automatically. Also you can double click on the drawing to open it. if you can implement that. That will be awesome

**Comment by jon-dez** [comment]
> Thats amazing Thanks you so much

No problem :slightly_smiling_face: 

> Will the edit button disappear?

Yes that is the plan :sunglasses: 

> Also you can double click on the drawing to open it. if you can implement that. That will be awesome

Will do :+1:

**Comment by MohamedKelif** [comment]
Thank you

**Comment by jon-dez** [comment]
@MohamedKelif Sorry it took me a while to get back to you on this issue, I have a video clip to present: 

https://github.com/user-attachments/assets/e98bc2e6-c313-4b56-aaed-7540980a2e81

If you think this is acceptable I will create a release for it. One thing to note, I decided to display a message instead of a button since double clicking the embed will open the editor.

**Comment by jon-dez** [comment]
https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.13.0

**Comment by MohamedKelif** [comment]
Hi there! Thanks a bunch for getting back to me so quickly. You're doing amazing work, and I really appreciate all your efforts. You're truly doing something special!

I went ahead and tested it on three devices: Windows, iPhone, and iPad. Here's what I found:

### For Windows Machine
1. Embedding the file works like a charm and opens up super fast! It would be awesome if we could skip the 'confirm page' since I've already set the location in the plugin settings. (Maybe something for the future?)
2. Reopening files works great too, and the double-click feature is spot on for Windows.

### For iPad and iPhone
1. Embedding the file usually works well, but sometimes I get a "Failed to Open" message.
2. Reopening doesn't work unless you tap a few times. It's not a bug, just that iOS and iPadOS don't seem to have a double-click gesture. I even tried using my Apple Pencil, but no luck there.

Maybe a long-press option for mobile and tablets could help? No rush, though; we can always use long-press to bring up the dialog and edit. I'm not sure about Android tablets, but others might be able to test this out.

### A Few Other Bugs I Found (Off-topic)
I think someone mentioned this in issue #66, but just wanted to let you know:
- There are random streak lines when writing with the Apple Pencil. It might be an iPad thing, not sure.
- The size and pen type keep going back to the original settings, no matter what you choose.

## New Issue I Noticed
I can open a new issue if you'd like, just let me know. But here's a quick mention:

I noticed the embed size is a bit small. I tried following your "Documentation for Embeds," but it was a bit tricky for someone without a coding background. What worked for me was using ![[<tldraw_markdown_file>|<embed_size>]]. For example, ![[<tldraw_markdown_file>|<800x1000>]] made the size bigger, and that did the trick. I didn't add "size =" because changes weren't showing up for some reason.

I also tried debugging by toggling the background and dotted background. The dotted background stretches to the document's width, but the actual background is a bit short. I think it might have to do with the canvas position, but I haven't figured it out yet.

Maybe adding a sizing option to the plugin settings could help, so we can tweak it without messing with Obsidian modifiers.

Thanks so much for all your hard work!

**Comment by jon-dez** [comment]
Thank you for the kind words :slightly_smiling_face: 

You can disable the confirmation pop-up in the settings, I think this is what you are looking for:

![image](https://github.com/user-attachments/assets/6d626226-8c4a-4dd3-b1bb-3e3e96092be1)

For iPad and iPhone, well really for devices that support touch gestures, the tap and hold gesture brings up the context menu for the embed. I think this is probably the best choice since it does allow for choosing to edit the drawing, plus other options that relate to the embed in the markdown document. I do think tough that it would make sense to add a double tap gesture for the embeds so that it navigates to an editor, so I'll keep that in mind. 

## The bugs that you mentioned:

- The streak lines

I don't have an iPad, so I cannot test this. If possible, could you record a screen capture?

- Size and pen type

Does this also occur in the editor on tldraw.com?

Also, just to double check what version of the plugin do you have installed?

## The new issue that you notice:

I haven't been too focused on the sizing of embeds as much, but if you open a new issue I'll try to make time for it.

**Comment by jon-dez** [comment]
@MohamedKelif I created a new release that adds a new tool which assists with automatically setting the bounds, so you no longer have to set them manually.
https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.14.0
